// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package storage

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          uuid.UUID
	Password    string
	Name        pgtype.Text
	Surname     pgtype.Text
	Description pgtype.Text
	Phone       string
	Country     pgtype.Text
	AvatarID    pgtype.Text
}
