// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user.sql

package storage

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    password,
    name, surname,
    description,
    phone,
    country,
    avatar_id
) VALUES (
    $1,
    $2, $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id
`

type CreateUserParams struct {
	Password    string
	Name        pgtype.Text
	Surname     pgtype.Text
	Description pgtype.Text
	Phone       string
	Country     pgtype.Text
	AvatarID    pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Password,
		arg.Name,
		arg.Surname,
		arg.Description,
		arg.Phone,
		arg.Country,
		arg.AvatarID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
